---
title: "Web Scraping Whoopsies"
author: "Manu Alcala + Jameson Carter"
format: 
    revealjs: 
        slide-number: c/t
        width: 1250
        height: 800
editor: visual
---

## What is web scraping? {video-loop="true"}

static vs dynamic

scraping vs crawling

## When is it worth it? {video-loop="true"}

commonly produced highly standardized data

getting data quickly is valuable

no download available, cannot get through to data provider

format remains consistent

## What makes it hard? {video-loop="true"}

takes time to code

sites might change

not always desired from site maintainers

## Demonstrative example {video-loop="true"}

Slides describing florida example

## Demonstrative example 2 {video-loop="true"}

Slides describing kaiser family foundation example

## Bullets

When you click the **Render** button a document will be generated that includes:

-   Content authored with markdown
-   Output from executable code

## Code

When you click the **Render** button a presentation will be generated that includes both content and the output of embedded code. You can embed code like this:

```{r}
1 + 1
```

## Thank You!  {background-video="web-surfer.mp4" background-video-loop="true" background-size="50px"}
